### PR TITLE
Reformat all C code with indent

### PR DESCRIPTION
**Pull request by tiran**

### CODE REVIEW

**Comment by encukou** [comment]
This supersedes #2, right?

**Comment by tiran** [comment]
Mostly, this PR doesn't contain the autopep8 rule from PR #2.

**Comment by encukou** [comment]
Outstanding pull requests that touch C code are:
* #164, which I can easily rebase myself
* #64, WIP changes for OPT_X_TLS_NEWCTX warnings

@tiran, are you OK rebasing #64 once I merge autoformatting for C?

No need to rebase this PR; I'll run the script just before committing.

**Comment by tiran** [comment]
Yes, I'll handle #64 myself. The PR needs some more work.

**Pull request merged**
