### PR TITLE
Fix ldapurl parsing fails when scheme is uppercase

### PR DESCRIPTION
**Pull request by dmulder**
Fixes issue mentioned in #280.

### CODE REVIEW

**Comment by encukou** [comment]
I'm not opposed to moving forward. But yes, this does need tests.

**Comment by dmulder** [comment]
@tiran do you have docs for the python-ldap test suite? I've never written a test for this project before.

**Comment by tiran** [comment]
> @tiran do you have docs for the python-ldap test suite? I've never written a test for this project before.

The tests are in ``Tests/`` directory. You can add some upper-case examples to this test class:

https://github.com/python-ldap/python-ldap/blob/7e084aec1ba9ced25b44fd3db77e65242a827806/Tests/t_ldapurl.py#L31-L53

**Comment by tiran** [comment]
I have opened PR https://github.com/python-ldap/python-ldap/pull/347 for you to get the fix into 3.3.0.

**Pull request closed without merging**
