### PR TITLE
[WIP] Add reproducer for start_tls issue with NSS

### PR DESCRIPTION
**Pull request by tiran**
See https://github.com/python-ldap/python-ldap/issues/60
Signed-off-by: Christian Heimes <cheimes@redhat.com>

### CODE REVIEW

**Comment by encukou** [comment]
Do we need this in the repository?
This seems better suited for a pastebin, e.g. (Gist)[https://gist.github.com/]

**Comment by tiran** [comment]
I'll convert it to a test case once the issue has been resolved.

**Comment by encukou** [comment]
Alright; if you don't need it in master then let's keep it WIP

**Comment by tiran** [comment]
Test case is in https://github.com/python-ldap/python-ldap/pull/134

**Pull request closed without merging**
