### PR TITLE
Make indent again

### PR DESCRIPTION
**Pull request by tiran**
Signed-off-by: Christian Heimes <cheimes@redhat.com>

### CODE REVIEW

**Comment by tiran** [comment]
We need a test for C indention.

**Comment by encukou** [comment]
The Travis job is consistently failing in coverage with `sqlite3.OperationalError`. Do you know how to fix this?
Myself, I'd be OK with removing the coverage report. It is very noisy; I don't really look at it.

**Comment by encukou** [comment]
Anyway, I checked that the actual tests pass.

**Comment by tiran** [comment]
> The Travis job is consistently failing in coverage with `sqlite3.OperationalError`. Do you know how to fix this?
> Myself, I'd be OK with removing the coverage report. It is very noisy; I don't really look at it.

Yes, ``coverage < 5.0`` is the fix for the SQLite operation error.

**Comment by encukou** [comment]
OK, I'll add it again.

**Comment by tiran** [comment]
Apparently only some builders are affected. Most test runs today did not fail.

**Pull request merged**
