### PR TITLE
Add retry on EINTR.

### PR DESCRIPTION
**Pull request by rgbyrnes**
Fixes https://github.com/python-ldap/python-ldap/issues/242.

### CODE REVIEW

**Comment by dmulder** [comment]
FYI, I was getting this error:
ldap.SERVER_DOWN: {'desc': "Can't contact LDAP server", 'errno': 4, 'info': 'Interrupted system call'}
I think my server really is unreachable, and applying this patch now causes an infinite loop in my code.

**Comment by rgbyrnes** [comment]
I'm surprised that you're seeing consistent, repeated errno == EINTR with ldap.SERVER_DOWN ... why would that happen?  We've been running with this patch for > 9 months and have never seen that.

I suppose it couldn't hurt to terminate the loop after some finite number of retries, but that sorta feels like it's covering up some other issue.  If you can reproduce the behavior, it would be interesting to strace.  Are you using OpenLDAP?

**Comment by encukou** [comment]
@dmulder Which server are you using?

**Comment by encukou** [comment]
No response :(
@rgbyrnes, would you mind terminating the loop? An exception is better than infinite loop – especially since this code has no tests.

**Comment by encukou** [comment]
Still no response :(
Please re-open this if you have any additional information.

**Pull request closed without merging**
