### PR TITLE
please deploy the latest also on PiPy

### PR DESCRIPTION
**Pull request by uzk-develop**
https://pypi.org/project/python-ldap/ 
last change: Mar 13, 2019 

the last change in https://github.com/python-ldap/python-ldap/blob/master/Lib/ldap/__init__.py is from 21 May 2019 and was not transfered to PyPi!

### CODE REVIEW

**Comment by tiran** [comment]
python-ldap 3.2.0 is the latest release. There hasn't been a release since last year.

**Comment by uzk-develop** [comment]
the last change in 
https://github.com/python-ldap/python-ldap/blob/master/Lib/ldap/__init__.py 
is from 21 May 2019 and was not transfered to PyPi! 

Mit freundlichen Grüßen,
Gert Römer

Universität zu Köln
Tel. 0221 470-4020



Von:    Christian Heimes <notifications@github.com>
An:     python-ldap/python-ldap <python-ldap@noreply.github.com>
Kopie:  uzk-develop <groemer@uni-koeln.de>, Author 
<author@noreply.github.com>
Datum:  16.04.2020 17:14
Betreff:        Re: [python-ldap/python-ldap] please deploy the latest 
also on PiPy (#327)



python-ldap 3.2.0 is the latest release. There hasn't been a release since 
last year.
?

**Comment by tiran** [comment]
I don't like your tone. You are unreasonable aggressive and demanding to borderline abusive.

python-ldap is an open source project. You are benefiting from the unpaid work of a lot of skilled engineers. You are not paying us and you don't have a service contract with us either. Therefore you don't have any moral or legal right to demand anything from us.

Here is what you should do instead:
- Close this PR, which is obviously bogus.
- Open an issue and tell us which problem you are facing with the current release 3.2.0.
- Ask nicely and politely for a new release.

**Comment by uzk-develop** [comment]
Sorry, but I don't understand your reaction. I resolved my problem by my 
own and Fix thread support check for Python 3 in the PyPi release.
All I wanted, that other user should benefit from that change.

**Comment by frenzymadness** [comment]
> Sorry, but I don't understand your reaction. I resolved my problem by my own and Fix thread support check for Python 3 in the PyPi release. All I wanted, that other user should benefit from that change.

Then, you should open an issue and describe what is the problem and how a new release can fix it.

**Comment by uzk-develop** [comment]
The file from Pypi : \python-ldap-3.2.0\Lib\ldap\__init__.py
still contains the python2 import thread in line 57

try:
  # Check if Python installation was build with thread support
  import thread
except ImportError:
  LDAPLockBaseClass = DummyLock
else:
  import threading
  LDAPLockBaseClass = threading.Lock

This issue was fixed in https://github.com/python-ldap/python-ldap/blob/master/Lib/ldap/__init__.py
whith the python 3 import threading in line 57 which works fine.

try:
  # Check if Python installation was build with thread support
  import threading
except ImportError:
  LDAPLockBaseClass = DummyLock
else:
  LDAPLockBaseClass = threading.Lock

Would you be so kind to unify the two versions? Thanks.

**Comment by encukou** [comment]
Thanks for opening issue #328.
Merging master into 3.0 does not make sense; any new release will be 3.2+. I'll close this PR.

**Pull request closed without merging**
