### PR TITLE
Test with Python 3.12

### PR DESCRIPTION
**Pull request by tiran**
- Add 3.12 to setup.cfg, tox, and GHA
- Use Ubuntu 22.04 except for Python 3.6
- Add weekly cronjob to run CI

### CODE REVIEW

**Comment by tiran** [comment]
The `%f` format operator was never supported. It's now raising an error in 3.12

https://docs.python.org/3.12/c-api/unicode.html#c.PyUnicode_FromFormat

**Review by droideck — APPROVED** [review]
Looks good! Ack

**Comment by tiran** [comment]
@droideck Could you please reconfigure CI to require `Ubuntu with Python pypy3.9` instead of `Ubuntu with Python pypy3`? `actions/setup-python@v4` requires a minor version for PyPy, too.

**Comment by droideck** [comment]
> @droideck Could you please reconfigure CI to require `Ubuntu with Python pypy3.9` instead of `Ubuntu with Python pypy3`? `actions/setup-python@v4` requires a minor version for PyPy, too.

Do you mean to modify your PR and change https://github.com/python-ldap/python-ldap/blob/main/.github/workflows/tox-fedora.yml ?
Because for ci.yml, I already see the change in this PR.

Or is there something in GitHub project settings that only maintainers can access? If so, I wasn't able to find... Any guidance is appreciated. :)

**Comment by tiran** [comment]
> Or is there something in GitHub project settings that only maintainers can access? If so, I wasn't able to find... Any guidance is appreciated. :)

It's a GitHub setting somewhere under branch protection / required status checks. `Ubuntu with Python pypy3` is a required test, but the test no longer exists.

**Comment by droideck** [comment]
> > Or is there something in GitHub project settings that only maintainers can access? If so, I wasn't able to find... Any guidance is appreciated. :)
> 
> It's a GitHub setting somewhere under branch protection / required status checks. `Ubuntu with Python pypy3` is a required test, but the test no longer exists.

That was it! Hidden under the branch `edit` button... Thanks!

**Pull request merged**
