### PR TITLE
Add valgrind target to check for memory leaks

### PR DESCRIPTION
**Pull request by tiran**
Signed-off-by: Christian Heimes <cheimes@redhat.com>

### CODE REVIEW

**Comment by encukou** [comment]
I'll look at this one after 3.0 beta.

**Comment by encukou** [comment]
The `python3` and the path suppression are Fedora-specific. That's as good a default as any, but it needs to be readily configurable.
I tried fixing this, does that look OK?

**Comment by tiran** [comment]
Use the makefile force, Luke :)

```
$(PYTHON_SUPP):
    @echo "Need support file"
    exit 1

valgrind: $(PYTHON_SUPP)
```

**Comment by encukou** [comment]
Ooh, shiny! Glad to be your apprentice :)

**Pull request merged**
