### PR TITLE
SlapdObject increasing waiting time

### PR DESCRIPTION
**Pull request by azmeuk**
This gives a chance to SlapdObject to start faster. Notably it does not start by sleeping 1.5s anymore.

### CODE REVIEW

**Comment by tiran** [comment]
The ``range()`` timeout loop is flawed because it may wait much longer than we want. A better approach is the set a deadline with a monotonic timer, do the work, check deadline and sleep in a while loop:

```
deadline = time.monotonic() + 10
while True:
    # do stuff
    if time.monotonic() >= deadline:
        break
    time.sleep(0.2)
```

**Comment by azmeuk** [comment]
Thank you, this is indeed a much cleaner way. This is fixed.

**Review by droideck — APPROVED** [review]
Looks good to me!

**Comment by azmeuk** [comment]
I just noticed that this patch had greatly diminished the `tox` execution time \o/

**Pull request merged**
