### PR TITLE
Merge pyldap + python-ldap

### PR DESCRIPTION
**Pull request by encukou**
This merges Michael's 2.5.x branch from CVS, and the pyldap project.

The result should be the same as in https://github.com/pyldap/pyldap/pull/142, except there's no deprecation note in the README.
edit: And the CHANGELOG is different

### CODE REVIEW

**Comment by encukou** [comment]
cc @tiran

**Comment by tiran** [comment]
Confirmed, only ``CHANGES`` and ``README`` are different.

```
pushd pyldap
git pr 142
git clean -xdf
popd
pushd python-ldap
git pr 4
git clean -xdf
popd
diff -ur -x.git python-ldap pyldap
```

**Comment by encukou** [comment]
Known issue: README formatting is wrong, but let's fix it up after commmitting this.

**Comment by tiran** [comment]
tox tests are passing on my machine

**Pull request merged**
